# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/new/src/opencv_BOF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/new/src/opencv_BOF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/new/src/opencv_BOF/CMakeFiles /home/new/src/opencv_BOF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/new/src/opencv_BOF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compareBOF

# Build rule for target.
compareBOF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compareBOF
.PHONY : compareBOF

# fast build rule for target.
compareBOF/fast:
	$(MAKE) -f CMakeFiles/compareBOF.dir/build.make CMakeFiles/compareBOF.dir/build
.PHONY : compareBOF/fast

#=============================================================================
# Target rules for targets named bow

# Build rule for target.
bow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bow
.PHONY : bow

# fast build rule for target.
bow/fast:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/build
.PHONY : bow/fast

bow.o: bow.cpp.o

.PHONY : bow.o

# target to build an object file
bow.cpp.o:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/bow.cpp.o
.PHONY : bow.cpp.o

bow.i: bow.cpp.i

.PHONY : bow.i

# target to preprocess a source file
bow.cpp.i:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/bow.cpp.i
.PHONY : bow.cpp.i

bow.s: bow.cpp.s

.PHONY : bow.s

# target to generate assembly for a file
bow.cpp.s:
	$(MAKE) -f CMakeFiles/bow.dir/build.make CMakeFiles/bow.dir/bow.cpp.s
.PHONY : bow.cpp.s

compareBOF.o: compareBOF.cpp.o

.PHONY : compareBOF.o

# target to build an object file
compareBOF.cpp.o:
	$(MAKE) -f CMakeFiles/compareBOF.dir/build.make CMakeFiles/compareBOF.dir/compareBOF.cpp.o
.PHONY : compareBOF.cpp.o

compareBOF.i: compareBOF.cpp.i

.PHONY : compareBOF.i

# target to preprocess a source file
compareBOF.cpp.i:
	$(MAKE) -f CMakeFiles/compareBOF.dir/build.make CMakeFiles/compareBOF.dir/compareBOF.cpp.i
.PHONY : compareBOF.cpp.i

compareBOF.s: compareBOF.cpp.s

.PHONY : compareBOF.s

# target to generate assembly for a file
compareBOF.cpp.s:
	$(MAKE) -f CMakeFiles/compareBOF.dir/build.make CMakeFiles/compareBOF.dir/compareBOF.cpp.s
.PHONY : compareBOF.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... compareBOF"
	@echo "... bow"
	@echo "... bow.o"
	@echo "... bow.i"
	@echo "... bow.s"
	@echo "... compareBOF.o"
	@echo "... compareBOF.i"
	@echo "... compareBOF.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

